server.port=8085
spring.application.name=notification-service

spring.data.mongodb.uri=mongodb://localhost:27017/event-app-notifications

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# JWT Secret (Must match Auth Service)
jwt.secret=MySecretKeyForEventApp1234567890MySecretKeyForEventApp1234567890
