server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1
        - id: participant-service
          uri: lb://participant-service
          predicates:
            - Path=/api/participants/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        - id: uploads
          uri: lb://event-service
          predicates:
            - Path=/api/uploads/**
          filters:
            - StripPrefix=1
        - id: uploads
          uri: lb://event-service
          predicates:
            - Path=/api/uploads/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
