server.port=3001
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/event_app_db
spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/uploads/**



# JWT settings
app.jwtSecret=VGhpc0lzQVRlc3QxMjM0NTZTZWN1cmVLZXlGb3JKV1Q=
app.jwtExpirationMs=3600000
