server.port=8081
spring.application.name=auth-service

spring.data.mongodb.uri=mongodb://localhost:27017/event-app-auth

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# JWT Secret (Copying from existing logic or defining new)
jwt.secret=MySecretKeyForEventApp1234567890MySecretKeyForEventApp1234567890
jwt.expiration=86400000
