server.port=8082
spring.application.name=user-service

spring.data.mongodb.uri=mongodb://localhost:27017/event-app-auth

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# JWT Secret (Must match Auth Service)
jwt.secret=MySecretKeyForEventApp1234567890MySecretKeyForEventApp1234567890
